apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: robotchenpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: robotchenpipelinesjavascriptdocker 
    spec:
      containers:
        - name: robotchenpipelinesjavascriptdocker 
          image: myreg4chen.azurecr.io/robotchenpipelinesjavascriptdocker 
          ports:
          - containerPort: 8080